### ISSUE TITLE
re: php 7.0

### ISSUE THREAD

**Issue by SignpostMarv** [paragonie/corner#2]
I've got some legacy environments that I unfortunately cannot upgrade to a recent version of PHP for the foreseeable future, and I have a teensy problem.

One of the legacy environments processes the composer autoloader in a funky way such that even though the the [shim interface is conditionally loaded](https://github.com/paragonie/corner/blob/1aa377c974be99fca6217dc67f360a1acd75d308/php5/Throwable.php#L2) it ends up causing issues when the native Throwable gets loaded.

How much of a pita would it be to have either a `^7.0,<7.1` point release on 1.x, or a random_compat:v9.99.99-style separate shim for Throwable ?

The specific issue is inherited from requiring paragonie/easydb:^2.8 on a `^7.0,<7.1` environment, but the workaround is to put a version cap on paragonie/easydb to one that doesn't load this package- so not such an urgent problem as yet.

~ SignpostMarv.

**Comment by SignpostMarv** [comment]
it turns out the workaround won't work, as **another** package in the project deployed in the legacy environment requires the affected version, so the workaround is now to add a namespaced stub to the project's git repo in `./vendor/paragonie/corner/php5/Throwable.php` to avoid it triggering the error.

yay legacy environments ¬_¬

**Comment by paragonie-scott** [comment]
I can add a shim to the v1.x branch.

**Comment by SignpostMarv** [comment]
ty very much :D

have spent the last day and a half at the day job tracking down an avalanche of issues caused by fixing each subsequent compatibility issue that was discovered.

the legacy environment isn't dockerised, so I've got local development with mostly the same versions of everything on windows, deployed on centos.

this particular issue does not occur on the windows machine, and i've no idea what aspect of the legacy environment means the php5 file gets loaded o_O

**Comment by SignpostMarv** [comment]
Resolved by using `mcaskill/composer-exclude-files` re: composer/composer#5029  ;

```json
{
    "autoload": {
        "exclude-from-files": [
            "./paragonie/corner/php5/Throwable.php"
        ]
    }
}
```
